# Generated by Django 2.2.7 on 2019-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.IntegerField(max_length=50)),
                ('fieldofStudy', models.CharField(max_length=50)),
                ('cryptoknowledge', models.CharField(max_length=50)),
                ('whatwoulddiscourageyou', models.CharField(max_length=50)),
            ],
        ),
    ]
