# Generated by Django 2.2.7 on 2019-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='someModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age_group', models.CharField(max_length=50)),
                ('crypto_knowledge', models.CharField(max_length=250)),
                ('crypto_use_followup', models.TextField(max_length=250)),
                ('crypto_discourage', models.CharField(max_length=250)),
                ('crypto_discourage_other', models.TextField(max_length=250)),
                ('crypto_encourage', models.TextField(max_length=250)),
                ('crypto_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
