# Generated by Django 2.2.7 on 2019-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191110_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='somemodel',
            name='crypto_encourage_other',
            field=models.TextField(default='Nan', max_length=250),
        ),
        migrations.AddField(
            model_name='somemodel',
            name='crypto_use',
            field=models.TextField(default='Nan', max_length=250),
        ),
        migrations.AddField(
            model_name='somemodel',
            name='field_of_study',
            field=models.CharField(default='Nan', max_length=250),
        ),
    ]
